# Generated by Django 2.0.3 on 2018-03-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='urls',
            name='longURL',
            field=models.CharField(max_length=500),
        ),
    ]
